# Generated by Django 4.1.4 on 2023-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_profile_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
