# Generated by Django 4.1.4 on 2023-02-23 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="save_by",
            field=models.ManyToManyField(
                related_name="has_saved", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
