# Generated by Django 4.1.4 on 2023-02-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_save_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="save_by", new_name="saved_by",
        ),
    ]
