# Generated by Django 4.1.4 on 2023-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_rename_save_by_post_saved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
